Change highlighting of today
nextcloud/calendar pull request #2522
Opened 2020-08-28 19:00 UTC by georgehrke

| Before | After |
|:---------:|:------:|
|![before](https://user-images.githubusercontent.com/1250540/91605732-38199b80-e971-11ea-95ae-2cd4c99b2289.jpg)|![after](https://user-images.githubusercontent.com/1250540/91605747-3cde4f80-e971-11ea-904c-4186ae59b7c8.jpg)|
|Week view: |![week_after](https://user-images.githubusercontent.com/1250540/91605794-51bae300-e971-11ea-984f-0a331ff584f2.jpg)|

I'm not happy about how it looks in day / week view.

please review and test @nextcloud/designers

At the last Calendar Design review session, we discussed how to improve the highlighting of today. This is what we came up with. It's similar to what Outlook Web does.

2020-08-28 19:15 UTC, SuperSandro2000 commented
I would make the entire top row blue and wouldn't move the number a pixel down.

2020-08-29 07:45 UTC, skjnldsv approved these changes

2020-08-31 08:32 UTC, juliushaertl commented
Any reason against a full cell highlight with a dimmed primary color? I must say i find both the before and after very hard to spot.

2020-08-31 08:36 UTC, georgehrke commented
> Any reason against a full cell highlight with a dimmed primary color? I must say i find both the before and after very hard to spot.

We used to have a full-cell yellow highlighting in the past, but that caused many issues because the visibility was very dependent on the display and screen settings. We got very mixed bug reports from some users for whom it was way too bright and then from others who couldn't even see it on their screens. That's why we stopped using the full cell highlight long time ago.

2020-08-31 08:42 UTC, georgehrke commented
For reference: iCloud does it similar to this PR, just that they also highlight the entire current week:
![97417048-6636-47E5-86CB-C5B9639D5657](https://user-images.githubusercontent.com/1250540/91700743-9ebbd680-eb76-11ea-88fb-2c5b67ea1e6d.png)

2020-09-02 13:02 UTC, ma12-co requested changes
Can we extend the highlight for the whole current week just like apple calendar does in the month view? It just makes it way faster to reach the current day at a glance.
it could be done with var(--color-priomary-light) maybe?

2020-09-02 16:11 UTC, tcitworld commented
Also in week view iCloud puts a light background on the whole day column.
![image](https://user-images.githubusercontent.com/2197836/92008661-bbf3cf00-ed47-11ea-9a3f-e76224503d1e.png)

2020-11-16 07:37 UTC, jancborchardt commented
> Any reason against a full cell highlight with a dimmed primary color? I must say i find both the before and after very hard to spot.

Would agree here. The previous highlight of the very present circle on the day number is definitely better (because it also makes clearer to which day it belongs and can’t be confused with the day above it), and an additional background of `var(--color-primary-light)` could do the trick.

2020-12-15 12:44 UTC, th23x commented
Great idea as the "Today" does not come out clearly initially.

I also had a look and styled this via some CSS - unfortunately not in the source code format, but only via theming. However maybe somebody would like to take it to develop further/ include in the suggested chage:

Result views:
![cal-month](https://user-images.githubusercontent.com/13735303/102216224-1ff76900-3edb-11eb-8afc-4b522601a79a.jpg)
![cal-week](https://user-images.githubusercontent.com/13735303/102216227-208fff80-3edb-11eb-87ed-d6e30f3d0441.jpg)
![cal-list](https://user-images.githubusercontent.com/13735303/102216230-208fff80-3edb-11eb-8c1c-9b0e7177e5e8.jpg)

Source CSS (month):
`.app-calendar .fc .fc-daygrid-day.fc-day-today {
	background: var(--color-primary-light);
}
.app-calendar .fc-day-today .fc-daygrid-day-number {
	border-radius: 0;
	margin: 0 0 6px 0;
	width: 100%;
	height: auto;
}`

Source CSS (week):
`.app-calendar .fc-day-today.fc-col-header-cell a,
.app-calendar .fc-day-today.fc-col-header-cell span {
	width: 100%;
	border-radius: 0;
}
.app-calendar .fc .fc-timegrid-col.fc-day-today {
	background: #fafafa;
}`

Source CSS (list):
`.app-calendar .fc-list-day.fc-day-today .fc-list-day-cushion {
	background: var(--color-primary-element);
}
.app-calendar .fc-list-day.fc-day-today .fc-list-day-cushion .fc-list-day-text,
.app-calendar .fc-list-day.fc-day-today .fc-list-day-cushion .fc-list-day-side-text {
	color: var(--color-primary-text);
	font-weight: bold;
}`

2021-01-05 09:12 UTC, alexanderdd commented
Hey, to me the new highlighting does not stick out enough visually. It looks exactly the same as events (rectangle). Please **make a screenshot with 6+ events per day, you will notice that it does not work**. (I notice a tendency in the calendar repo to use empty or nearly empty calendars for testing screenshots -- my calendars are full, and that is when I need highlighting the most). Also, just because Outlook an iCloud are doing it, we don't have to do it the same way.

The circle is better. OR "full cell highlight with a dimmed primary color" as suggested by @juliushaertl (businesscalendar2 android app does that).

2022-06-18 14:19 UTC, szaimen commented
not needed anymore

2022-06-18 14:19 UTC, closed without merging