Set task start to allow visualization as regular event
nextcloud/calendar pull request #3033
Opened 2021-04-20 07:41 UTC by foxtrotzulu94

This PR enables tasks to be visualized as regular events, when their start date is available. Fixes #2669 and will primarily affect Day and Week views of any calendar. See attached screenshots for reference.

![image](https://user-images.githubusercontent.com/6027890/115356991-04de8380-a171-11eb-895a-32b437663555.png)

2021-04-20 08:34 UTC, tcitworld requested changes
Can you fix eslint issues and have a look at the failed test?

Not sure about this one, as some people may have tasks ongoing for several days/weeks/months, they only care about the due date and don't want it to pollute their calendar.

2021-04-24 01:12 UTC, foxtrotzulu94 commented
> 
> 
> Can you fix eslint issues and have a look at the failed test?
> 
> Not sure about this one, as some people may have tasks ongoing for several days/weeks/months, they only care about the due date and don't want it to pollute their calendar.

Thanks for taking a look. Issues have been fixed!

And what you pointed out in terms of people not wanting to pollute their calendars was one of my worries as well. I've been testing out the change for a couple of days now and ran into this as well. Maybe it can be controlled through another configuration setting in the future?

2021-09-30 14:33 UTC, szaimen commented
What would be more useful instead (IMO) would be putting tasks into the all-day section only (also the ones that have a time set) and also showing tasks that are overdue and not done yet always only in the all-day section of today.
This is how Google Calendar handles this.
Then the tasks don't completely polute the calendar view and you will be able to work in a useful way with them.

@foxtrotzulu94 @jancborchardt @nimisha-vijay  what do you think about that?

2023-02-06 17:47 UTC, krillin666 commented
Is there any update on this (very essential) PR?

2023-03-26 13:16 UTC, asandikci commented
Is there any update for this feature? I think this is really necessary. And there could be a configuration in the settings for people who don't want this feature and don't want to pollute their calendars 
@foxtrotzulu94

2026-09-01 17:41 UTC, Rudd-O commented
Also fixes https://github.com/nextcloud/calendar/issues/8824 .

2026-09-01 17:42 UTC, Rudd-O commented
Can someone please help pushing this through?

2026-09-01 17:42 UTC, Rudd-O commented
> Is there any update for this feature? I think this is really necessary. And there could be a configuration in the settings for people who don't want this feature and don't want to pollute their calendars @foxtrotzulu94 @tcitworld

It is already possible to turn off task display in calendar.  It's in the settings.

2026-09-01 18:02 UTC, Rudd-O commented
@foxtrotzulu94 I have taken the liberty of fixing your merge conflict here:

https://github.com/Rudd-O/calendar/tree/issue/2669-task-start-date

Anyone is free to reopen the PR using my branch — but I would prefer if the original author cherry-picked and took credit for my change.

2026-09-01 18:04 UTC, Rudd-O commented
Actually Javier is no longer active on GH so I will open my own PR.

2026-09-05 19:56 UTC, SebastianKrupinski commented
Supersede by https://github.com/nextcloud/calendar/pull/8825

2026-09-05 19:56 UTC, closed without merging