l10n: Extract a space from the translation
nextcloud/calendar pull request #3080
Opened 2021-05-15 09:30 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2021-05-15 09:36 UTC, tcitworld requested changes
Nope, the variable should be brought into the translation instead of concatening.

2021-05-15 09:42 UTC, Valdnet commented
Corrected variable, but I don't know if the bot will scan the text string correctly.

@tcitworld Is it ok now?

2021-05-15 09:50 UTC, raimund-schluessler commented on lib/Controller/EmailController.php
> +			'message' => $this->l10n->t('Successfully sent email to' . ' ' . $recipient),
@Valdnet I think @tcitworld meant something like this (not tested):
```suggestion
			'message' => $this->l10n->t('Successfully sent email to %1$s', $recipient),
```

2021-05-15 11:09 UTC, rakekniven approved these changes

2021-05-15 22:29 UTC, tcitworld requested changes

2021-05-15 22:29 UTC, tcitworld commented on lib/Controller/EmailController.php
> +			'message' => $this->l10n->t('Successfully sent email to %1$s', $recipient),
CI says it should be an array.
```suggestion
			'message' => $this->l10n->t('Successfully sent email to %1$s', [$recipient]),
```

2021-05-16 14:36 UTC, tcitworld approved these changes

2021-05-16 15:23 UTC, merged