Show shared calendars by default
nextcloud/calendar pull request #3159
Opened 2021-06-06 21:00 UTC by burnoutberni

Changes the `enabled` default behavior. Instead of hiding shared calendars by default, now they are shown and users instead have to manually disable shared calendars in order to hide them. Fixes #3022.

2021-06-07 06:56 UTC, ChristophWurst requested changes
Let's first discuss https://github.com/nextcloud/calendar/issues/3022#issuecomment-855645920

2021-06-11 06:01 UTC, ChristophWurst approved these changes

2021-06-11 06:01 UTC, ChristophWurst commented
CI is not happy. Please check the test out and sign off your commits for the DCO

2021-06-11 18:54 UTC, burnoutberni commented
Thanks, @rponline, I'm closing my PR in favor of yours.

2021-06-11 18:54 UTC, closed without merging