Add plus-icon for AppNavigationHeaderNewEvent
nextcloud/calendar pull request #3950
Opened 2022-02-11 16:04 UTC by JuliaKirschenheuter

fixes #3945

2022-02-11 16:16 UTC, tcitworld requested changes

2022-02-11 16:16 UTC, tcitworld commented on src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
> +		<Plus :size="20" decorative />
The `decorative` prop [has been removed](https://github.com/robcresswell/vue-material-design-icons/releases/tag/5.0.0) in vue-material-design-icons 5.0.0.

2022-02-14 08:08 UTC, tcitworld approved these changes

2022-02-14 08:19 UTC, ChristophWurst commented
>  ERROR in src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
>  54:4  ✖  Expected indentation of 2 tabs  indentation
>  55:4  ✖  Expected indentation of 2 tabs  indentation

2022-02-14 08:20 UTC, ChristophWurst requested changes

2022-02-14 08:20 UTC, ChristophWurst commented on src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
> +	  Plus,
```suggestion
		Plus,
```

2022-02-22 13:16 UTC, ChristophWurst commented
The build still fails

```
ERROR in src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
 54:4  ✖  Expected indentation of 2 tabs  indentation
 55:4  ✖  Expected indentation of 2 tabs  indentation
```

2022-02-22 13:16 UTC, ChristophWurst commented on src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
> +			align-items: center;
```suggestion
		display: flex;
		align-items: center;
```

2022-02-23 10:07 UTC, merged