Fix navigation icon bullet accessibility
nextcloud/calendar pull request #3960
Opened 2022-02-16 13:16 UTC by JuliaKirschenheuter

use CheckboxBlankCircle as icon within the Action for icon bullet instead of AppNavigationIconBullet and AppNavigationDisabledCalendarIconBullet.

AppNavigationDisabledCalendarIconBullet is not needed anymore.

fixes #3955 
fixes #3966

- [x] Requires https://github.com/nextcloud/nextcloud-vue/pull/2506

2022-02-16 15:23 UTC, GretaD commented
is this ready for review? also, how to test it?

2022-02-17 14:19 UTC, JuliaKirschenheuter commented
@nimishavijay 
i have done some small UI changes (only calendar app, only sidebar), please approve it if it is ok.

now (with focus on circle):
![image](https://user-images.githubusercontent.com/6078378/154500126-b6cd8e4e-91b4-43d9-87ff-0d5c73003753.png)

before (without focus on circle): 
![image](https://user-images.githubusercontent.com/6078378/154500404-d18631b4-28d7-4cbf-ab4e-07a426c0ef75.png)

2022-02-17 14:20 UTC, JuliaKirschenheuter commented
fixes #3955

2022-02-17 14:27 UTC, nimishavijay approved these changes
Looks great design wise! 🚀

2022-02-17 14:39 UTC, ChristophWurst commented
this requires changes in nc/vue, doesn't it?

2022-02-23 10:14 UTC, ChristophWurst requested changes

2022-02-23 10:14 UTC, ChristophWurst commented on src/components/AppNavigation/CalendarList/CalendarListItem.vue
> +							:title="isCalendarEnabled ? $t('calendar', 'Disable calendar') : $t('calendar', 'Enable calendar') "
```suggestion
							:title="calendar.enabled ? $t('calendar', 'Disable calendar') : $t('calendar', 'Enable calendar') "
```

that is simple enough and doesn't require an additional computed property. same is used two lines below

2022-02-23 10:14 UTC, ChristophWurst commented on src/components/AppNavigation/CalendarList/CalendarListItem.vue
> +import CheckboxBlankCircle from 'vue-material-design-icons/CheckboxBlankCircle.vue'
move up so the icons are sorted alphabetically

2022-02-23 13:32 UTC, merged

2022-02-23 13:35 UTC, ChristophWurst commented
/backport to stable3.0

2022-02-23 13:47 UTC, JuliaKirschenheuter commented
/backport to stable3.1