Replace deprecated String.prototype.substr()
nextcloud/calendar pull request #4104
Opened 2022-03-24 14:24 UTC by CommanderRoot

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

2022-03-24 14:27 UTC, tcitworld approved these changes
Thanks for making IDEs happy! 🙂

2022-03-24 14:29 UTC, raimund-schluessler approved these changes

2023-01-17 09:36 UTC, st3iny requested changes
**Warning:** `substr()` and `slice()` don't behave in the same way!

```
substr(start)
substr(start, length)
```

```
slice(indexStart)
slice(indexStart, indexEnd)
```

The method `substr()` takes a length as its second param while `slice()` takes an index. Usages with only the first argument behave the same way and don't need to be refactored.

2023-01-17 09:36 UTC, st3iny commented on src/store/calendars.js
> +		const objectFileName = objectPath.slice(lastSlashIndex + 1)
Needs to be adjusted.

2023-01-17 09:36 UTC, st3iny commented on src/utils/color.js
> +		return '#' + color.slice(0, 6)
Needs to be adjusted.

2023-01-17 09:39 UTC, st3iny approved these changes
Nevermind, all extended usages start with a 0 index and thus behave in the same way.

2023-01-17 09:43 UTC, merged