add ok-button to datetime picker
nextcloud/calendar pull request #4105
Opened 2022-03-24 15:20 UTC by newhinton

This closes #2936.

The goal is to create a more "guided" user experience by providing explicit actions to confirm an action

2022-04-03 18:23 UTC, szaimen commented
@newhinton thanks for this PR! Could you please fix the CI? Thank you! :)

2022-04-05 14:27 UTC, newhinton commented
I have found out how the contacts-app does it. However: This comes with a drawback.

Clicking outside now dismisses the picker, without changing the date.
Selecting a date/time does not save it. The user now HAS to click the confirm button.

While they present a drastic change to the current behaviour, i still think this is the way forward, to keep consistency and a clear functionality which the current implementation does not provide.

2022-04-05 23:07 UTC, szaimen commented
> I have found out how the contacts-app does it. However: This comes with a drawback.
> 
> Clicking outside now dismisses the picker, without changing the date. Selecting a date/time does not save it. The user now HAS to click the confirm button.
> 
> While they present a drastic change to the current behaviour, i still think this is the way forward, to keep consistency and a clear functionality which the current implementation does not provide.

cc @jancborchardt and @nimishavijay on that

2022-04-07 07:56 UTC, jancborchardt commented
I'd say that's ok. @nimishavijay what do you think?

2022-04-12 09:38 UTC, nimishavijay commented
Yep this sounds like a good idea! Suggestion: we could use "Done" for the wording in the button.

2022-04-12 17:46 UTC, newhinton commented
I dont really know if that is easily possible. Even the `confirm` element is not documented in the nextcloud/vue project, and i have not yet found a way to access the `confirmText` value in the underlying datetimepicker library. Maybe we need to first expose this in the vue project?

2022-04-12 18:00 UTC, szaimen approved these changes
I like it and it works :)
| ![image](https://user-images.githubusercontent.com/42591237/163024892-628b6436-be73-4c7e-8fba-09f37ffebef2.png) | ![image](https://user-images.githubusercontent.com/42591237/163025059-c8b26a2d-7882-4d74-92f2-221546e2fa03.png) |

2022-04-12 18:01 UTC, szaimen commented
@newhinton can you please resolve DCO? Afterwards we can merge this, imo :)

2022-04-12 18:25 UTC, newhinton commented
@szaimen Yes i will fix that! But i wanted to add a 5px margin between the buttons beforehand if thats fine with you

2022-04-12 18:26 UTC, szaimen commented
> But i wanted to add a 5px margin between the buttons beforehand if thats fine with you

Of course it is fine, please go ahead :)

2022-04-12 19:51 UTC, newhinton commented
it's a 4 pixel margin now, to keep it centered. However, as you can see in your own screenshot, we may have to adjust the popup width so that the controls always fit inside the popup. My margin has worsened it. Should i try to fix it here aswell?

2022-04-13 09:33 UTC, nimishavijay commented
Looks good to me! I have one important point though: Considering the date/time will be selected only after you click "OK", the button should really be in the primary button style, i.e `--color-primary` background with `--color-primary-text` text. Currently it looks more like a disabled button.

2022-04-13 09:42 UTC, szaimen commented
> Looks good to me! I have one important point though: Considering the date/time will be selected only after you click "OK", the button should really be in the primary button style, i.e `--color-primary` background with `--color-primary-text` text. Currently it looks more like a disabled button.

In general this should probably be adressed in the vue repo but @newhinton do you think we are able to overwrite the color somehow?

2022-04-13 10:13 UTC, newhinton commented
@szaimen probably. Though maybe we should just fix it in the vue repo, so that the contacts app (and everyone else) benefits aswell. 

I think i will create a pr for the vue repo, and not touch it here if it is okay, (that includes the misaligned text&margins, though we already have one now. Should i remove that then?)

2022-04-13 11:15 UTC, szaimen commented
> Though maybe we should just fix it in the vue repo, so that the contacts app (and everyone else) benefits aswell.
> 
> I think i will create a pr for the vue repo, and not touch it here if it is okay. (that includes the misaligned text&margins, though we already have one now. Should i remove that then?)

Sounds good to me!
@nimishavijay also fine to you?

2022-04-14 10:07 UTC, st3iny requested changes
Tested and works. Please squash your commits into one before we can merge.

2022-04-19 07:15 UTC, newhinton commented
I have removed the margin for now.

2022-04-19 09:49 UTC, merged