Fix issue with Attendee not being string crashing tooltip
nextcloud/calendar pull request #5170
Opened 2023-04-28 17:35 UTC by masonbrothers

There is an issue when you upload a new ics file to nextcloud calendar that does not contain attendees.

Since there is an assumption that the attendee is going to be a string (and not undefined), the tooltip crashes when you try to edit an event.

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at b9 (attendee.js:30:10)
    at o.userAsAttendee (EditorMixin.js:234:22)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.userAsAttendee (vue.runtime.esm.js:5537:25)
    at o.isViewedByAttendee (EditorMixin.js:222:16)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.isViewedByAttendee (vue.runtime.esm.js:5537:25)
    at o.<anonymous> (EditSimple.vue:1:4915)
```

This PR should fix this by coercing non strings to become strings.

2023-05-03 11:28 UTC, ChristophWurst commented on src/utils/attendee.js
> +	if (typeof uri !== 'string') return ''
```suggestion
	if (typeof uri !== 'string') {
		return ''
	}
```

2023-05-03 11:28 UTC, miaulalala requested changes

2023-05-03 11:28 UTC, miaulalala commented on src/utils/attendee.js
> +	if (typeof uri !== 'string') return ''
Please wrap your ifs
```suggestion
	if (typeof uri !== 'string')  {
	     return ''
	}
	     
```

2023-05-03 16:45 UTC, masonbrothers commented on src/utils/attendee.js
> +	if (typeof uri !== 'string') return ''
Thanks! Will do next time I submit!

2023-05-03 16:47 UTC, masonbrothers commented on src/utils/attendee.js
> +	if (typeof uri !== 'string') return 'mailto:'
```suggestion
	if (typeof uri !== 'string') {
		return 'mailto:'
	}
```

2023-05-04 11:29 UTC, miaulalala approved these changes

2023-05-04 11:29 UTC, merged

2023-05-04 11:29 UTC, miaulalala commented
Thanks for the PR!

2023-06-16 12:58 UTC, pierreozoux commented
Thanks a lot \o/ Have a wonderful weekend!