feat: Ability to invite circles
nextcloud/calendar pull request #5420
Opened 2023-08-18 16:09 UTC by onny

Partly fixes https://github.com/nextcloud/calendar/issues/2954

Work inspired by @tcitworld PR https://github.com/nextcloud/calendar/pull/4742

2023-09-05 07:54 UTC, st3iny commented
Hey, I just saw this PR and wanted to thank you for tackling this. Could you please add more context to the PR so that we can proceed, e.g what needs to be done and a short description?

It certainly is a nice feature :)

2023-10-02 15:10 UTC, onny commented
> Hey, I just saw this PR and wanted to thank you for tackling this. Could you please add more context to the PR so that we can proceed, e.g what needs to be done and a short description?
> 
> It certainly is a nice feature :)

Tank you for your interest. Currently thinking on how to query circle information and the circle members with their email addresses all at once with one request. Propably I'll have to add an additional backend controller / api?

2023-10-09 13:17 UTC, onny commented
This is the current state of both PRs combined (rendering groups & invite circles) 🥳 

![nextcloud-calendar-invite-circles](https://github.com/nextcloud/calendar/assets/757752/462ad595-a5dd-4f33-8761-90c389bb866f)

2023-10-16 12:52 UTC, onny commented
@miaulalala @jancborchardt @nimishavijay @tcitworld @st3iny I tested and simplified the PR a bit more, would be nice to know if there's anything missing :)

2023-10-18 16:13 UTC, onny commented
Thank you for reviewing :) Fixed it!

![image](https://github.com/nextcloud/calendar/assets/757752/84dc667a-9dda-4cbe-93f9-e032bc3793d3)

2023-10-23 14:47 UTC, miaulalala requested changes
Testing this currently.

First thing - the circle membership is unclear with the list of attendees like this:

![image](https://github.com/nextcloud/calendar/assets/7427347/02f1d4e2-69cc-47d4-af98-fc08c37b4bb4)

I don't know if it would be possible to have the members displayed as a sub- group. Quick'n'dirty mockup:

![image](https://github.com/nextcloud/calendar/assets/7427347/9bd57190-f416-4f36-a735-d38cf95d037f)

cc @jancborchardt 

It also sends an invitation email to the one creating the event if they are also a member of the circle. In principle, the ORGANIZER can also be an ATTENDEE, so it's not technically wrong, but it creates awkward visuals as well because the calendar app will show me the accept/decline buttons on an event that I made:

![image](https://github.com/nextcloud/calendar/assets/7427347/50ee0d3c-4a28-4367-b4ab-cdff90ad63f8)

Plus I'm a bit concerned about side effects for singificant changes and other stuff if I'm both ORGANIZER and ATTENDEE.

I think it's neccessary to filter out the circle member that is the organizer if that is the case and not set them as an attendee.

Other than that it works flawlessly and I'm super grateful @onny!

2023-10-23 14:50 UTC, miaulalala commented
Ah, does https://github.com/nextcloud/calendar/pull/5396 address the comments from above about the display?

2023-10-27 11:36 UTC, onny commented
@miaulalala I adjusted the code so that the organizer of the event doesn't get imported from the circle :)

2023-10-27 12:11 UTC, miaulalala commented
> @miaulalala I adjusted the code so that the organizer of the event doesn't get imported from the circle :)

I will test it today, thanks a lot!

2023-10-30 15:34 UTC, miaulalala reviewed
Looks good! I had a merge conflict that's why it didn't work for me. CI is unhappy, maybe a rebase on main will help.

2023-10-31 15:44 UTC, onny commented on src/models/attendee.js
> +		// TODO Expose member attribute in calendar-js
```suggestion
		// TODO Expose member attribute in calendar-js
```
easy workaround but propably going to fix this in calendar-js first

2023-11-02 11:36 UTC, jancborchardt approved these changes
Giving my design thumbs up already. :)

2023-11-02 12:14 UTC, miaulalala requested changes
Hi onnny, seems CI isn't happy still. 

You will need to run the linter for both PHP (composer cs:fix) and npm (npm run lint:fix). 

Additionally, the exposes internals of the Circles app, that's why statana is complaining here:
`lib/Controller/ContactController.php:212:14: UndefinedClass: Class, interface or enum named OCA\Circles\Api\v1\Circles does not exist `.

The contacts app also retrieves the circles, but via vue: https://github.com/nextcloud/contacts/blob/77771dc2bbca87ea0b108f21192642678eb8dd5d/src/components/AppContent/CircleContent.vue#L112C23-L112C23

I think it's neccessary to move the circle search to the frontend. Sorry about the late change request!

2023-11-05 11:34 UTC, onny commented
> Additionally, the exposes internals of the Circles app, that's why statana is complaining here: `lib/Controller/ContactController.php:212:14: UndefinedClass: Class, interface or enum named OCA\Circles\Api\v1\Circles does not exist `.

Maybe I need to figure out how to access the class only if the circles app is enabled and available?

> The contacts app also retrieves the circles, but via vue: https://github.com/nextcloud/contacts/blob/77771dc2bbca87ea0b108f21192642678eb8dd5d/src/components/AppContent/CircleContent.vue#L112C23-L112C23
> 
> I think it's neccessary to move the circle search to the frontend. Sorry about the late change request!

This was my first approach but I guess it's not possible to resolve the user mail addresses via the frontend. My backend controller queries all circle members and then resolves the mail addresses for local users: https://github.com/nextcloud/calendar/blob/7b15357772b98a2e109733e5d3dbde50a2e4afde/lib/Controller/ContactController.php#L239

2023-11-07 12:39 UTC, miaulalala requested changes
Hi onny, I fixed the tests locally, so if you implement the suggestions it should run through. You will also need an additional entry in `psalm.xml`.

Thanks for your hard work - @ChristophWurst and I have agreed since Circles is such a mess and has no public API, it's fine to leave the backend code as is. If you want you can add a comment above the call to the private API in that regard as well that this has been approved but us.

Looking forward to see this in action!!!! :heart_eyes:

2023-11-07 12:39 UTC, miaulalala commented on tests/php/unit/Controller/ViewControllerTest.php
>  				['spreed', true, '12.0.0'],
```suggestion
				['spreed', true, '12.0.0'],
				['circles', true, '22.0.0'],

```

2023-11-07 12:39 UTC, miaulalala commented on tests/php/unit/Controller/ViewControllerTest.php
>  				['spreed', true, '11.3.0'],
```suggestion
				['spreed', true, '11.3.0'],
				['circles', true, '22.0.0'],

```

2023-11-07 12:39 UTC, miaulalala commented on psalm.xml
> +				<referencedClass name="OCA\Calendar\Controller\Exception" />
```suggestion
				<referencedClass name="OCA\Calendar\Controller\Exception" />
				<referencedClass name="OCA\Circles\Api\v1\Circles" />
```

2023-11-07 12:39 UTC, miaulalala commented on lib/Controller/ViewController.php
> +		$isCircleVersionCompatible = $this->compareVersion->isCompatible($circleVersion ? $circleVersion : '0.0.0', '22');
```suggestion
		$isCircleVersionCompatible = $this->compareVersion->isCompatible($circleVersion ?? '0.0.0', '22');
```

2023-11-07 12:40 UTC, miaulalala requested changes

2023-11-07 12:40 UTC, miaulalala commented on tests/php/unit/Controller/ViewControllerTest.php
> +				['talk_api_version', 'v1'],
```suggestion
				['talk_api_version', 'v4'],
```

2023-11-07 18:16 UTC, onny commented
Thank you @miaulalala and @ChristophWurst for the review. Added the requested changes to the PR :)

2023-11-17 19:36 UTC, onny commented
@miaulalala I refactored the code which computes groups and memberships a bit to be more robust and simple. Works quite good for me now :)
Still have a look at the PHP linting errors etc 👀

2023-12-04 11:35 UTC, jancborchardt commented
@onny did anything change design-wise? Cause otherwise I would say it is still fine. :)

2023-12-04 15:03 UTC, miaulalala commented
@onny can you rebase on the current main? Tests will pass again, then I will take a look at the linter issues.

2023-12-04 17:36 UTC, onny commented
> @onny did anything change design-wise? Cause otherwise I would say it is still fine. :)

I refactored the code in `src/components/Editor/Invitees/InviteesList.vue` which computes groups and memberships a bit to be more robust and simple

@miaulalala Rebased the PR

2023-12-05 09:28 UTC, miaulalala commented
@ChristophWurst codecov coverage is complaining, am I ok to ignore? I would like to get this merged today 😊

2023-12-05 09:31 UTC, ChristophWurst commented
The circles code is probably pain to create test for due to the lack of a stable API so I'll wave this through

2023-12-05 09:35 UTC, miaulalala commented
> The circles code is probably pain to create test for due to the lack of a stable API so I'll wave this through

I'll test this one last time during lunch time and then I'll force merge.

Thanks so much for your work and patience @onny !

2023-12-05 10:17 UTC, jancborchardt approved these changes
Still looks good design-wise :)

2023-12-05 10:21 UTC, miaulalala approved these changes
Perfect!

2023-12-05 10:21 UTC, merged