chore(CI): Adjust testing matrix for Nextcloud 28 on main
nextcloud/calendar pull request #5589
Opened 2023-11-23 11:57 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2023-11-23 11:58 UTC, nickvergessen commented on .github/workflows/php-test.yml
>        run: echo "<?php" > nextcloud/lib/versioncheck.php
🙈

2023-11-30 10:29 UTC, miaulalala approved these changes

2023-11-30 10:40 UTC, miaulalala requested changes

2023-11-30 10:40 UTC, miaulalala commented on .github/workflows/php-test.yml
>              nextcloud-versions: 'master'
already adjusted, can be reverted.

2023-12-22 08:20 UTC, tcitworld commented
Do we need this at all anymore? Both `master` and `stable28` are already compatible with 8.3.

2023-12-22 09:12 UTC, closed without merging