Migrate/vuex to pinia
nextcloud/calendar pull request #5705
Opened 2024-01-21 20:47 UTC by GVodyanov

Close https://github.com/nextcloud/calendar/issues/5686 as part of https://github.com/nextcloud/groupware/issues/64

Continuation of https://github.com/nextcloud/calendar/issues/5685

TODO:
- [x] Migrate setting store
- [ ] Update settings store usage (in progress)
- [ ] Migrate principals store
- [ ] Update principals store usage
- [ ] Migrate importState store
- [ ] Update importState store usage
- [ ] Migrate importFiles store
- [ ] Update importFiles store usage
- [ ] Migrate fetchedTimeRanges store
- [ ] Update fetchedTimeRanges store usage
- [ ] Migrate davRestrictions store
- [ ] Update davRestrictions store usage
- [ ] Migrate contacts store
- [ ] Update contacts store usage
- [ ] Migrate calendars store
- [ ] Update calendars store usage
- [ ] Migrate calendarObjects store
- [ ] Update calendarObjects store usage 
- [ ] Migrate calendarObjectsInstance store
- [ ] Update calendarObjectsInstance store usage

2024-05-22 08:54 UTC, st3iny requested changes
First batch

I tested most changes locally.

2024-05-22 08:54 UTC, st3iny commented on src/components/CalendarGrid.vue
> +			'skipPopover',
```suggestion
```

Unused

2024-05-22 08:54 UTC, st3iny commented on src/components/CalendarGrid.vue
> +			'timezone',
```suggestion
```

Unused

2024-05-22 09:01 UTC, st3iny commented on npm
Done

2024-05-22 09:01 UTC, st3iny commented on src/components/AppNavigation/EditCalendarModal.vue
> +			return foundCalendar
Done

2024-05-22 09:02 UTC, st3iny commented on src/components/AppNavigation/Settings.vue
> -		Multiselect,
Done

2024-05-22 09:02 UTC, st3iny commented on src/store/calendars.js
> +			return this.sortedCalendars.filter((calendar) => {
Done

2024-05-24 09:39 UTC, st3iny submitted a review, later dismissed
Second batch. One more left.

2024-05-24 09:39 UTC, st3iny commented on src/mixins/EditorMixin.js
> +			this.calendarObjectInstanceStore.existingEvent.recurrenceId = null
I don't like inlining this into a mixin/component. I'll push a commit to move it back to the store.

Inlining within a store is okay, IMO.

2024-05-24 14:01 UTC, st3iny reviewed
Third batch done. Now, only manual testing is left.

2024-06-02 16:06 UTC, GVodyanov commented
I also did some clicking around and everything seems to be working well, thanks @st3iny!

2024-06-25 12:00 UTC, miaulalala commented
Error in ListView when opening the sidebar for a readonly event:

```
[Vue warn]: Missing required prop: "name"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
[Vue warn]: Error in mounted hook: "TypeError: this.$refs.header is undefined"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
TypeError: this.$refs.header is undefined
    focus NcAppSidebar-CQWODfsy.mjs:681
    mounted NcAppSidebar-CQWODfsy.mjs:562
    VueJS 18
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    step vue-router.esm.js:2084
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    routeEnterGuard vue-router.esm.js:2542
    beforeRouteEnter EditorMixin.js:686
    routeEnterGuard vue-router.esm.js:2535
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    runQueue vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2397
    step vue-router.esm.js:2084
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    resolveAsyncComponents vue-router.esm.js:2162
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    step vue-router.esm.js:2091
    step vue-router.esm.js:2091
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    created CalendarGrid.vue:235
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    __WEBPACK_DEFAULT_EXPORT__ windowTitleService.js:42
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    runQueue vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2606
    push vue-router.esm.js:3036
    push vue-router.esm.js:3035
    handleEventClick eventClick.js:82
    __WEBPACK_DEFAULT_EXPORT__ eventClick.js:37
    trigger internal-common.js:3680
    node_modules calendar-main.js:183014
    node_modules calendar-main.js:183880
    listenBySelector internal-common.js:270
    EventClicking index.js:1783
    node_modules calendar-main.js:183098
    node_modules calendar-main.js:183098
    node_modules calendar-main.js:194522
    setRef internal-common.js:2380
    node_modules calendar-main.js:186150
    Preact 22
vue.runtime.esm.js:3065
[Vue warn]: Missing required prop: "name"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().

found in

---> <NcDialog>
       <AttachmentsList> at src/components/Editor/Attachments/AttachmentsList.vue
         <NcAppSidebarTab>
           <NcAppSidebarTabs>
             <Fragment>
               <NcAppSidebar>
                 <EditSidebar> at src/views/EditSidebar.vue
                   <NcContent>
                     <Calendar> at src/views/Calendar.vue
                       <App> at src/App.vue
                         <Root> vue.runtime.esm.js:4625
[Vue warn]: Missing required prop: "showHeader"

found in

---> <InviteesList> at src/components/Editor/Invitees/InviteesList.vue
       <NcAppSidebarTab>
         <NcAppSidebarTabs>
           <Fragment>
             <NcAppSidebar>
               <EditSidebar> at src/views/EditSidebar.vue
                 <NcContent>
                   <Calendar> at src/views/Calendar.vue
                     <App> at src/App.vue
                       <Root> vue.runtime.esm.js:4625
```

Same for month view:

```
[Vue warn]: Missing required prop: "name"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
[Vue warn]: Error in mounted hook: "TypeError: this.$refs.header is undefined"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
TypeError: this.$refs.header is undefined
    focus NcAppSidebar-CQWODfsy.mjs:681
    mounted NcAppSidebar-CQWODfsy.mjs:562
    VueJS 18
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    step vue-router.esm.js:2084
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    routeEnterGuard vue-router.esm.js:2542
    beforeRouteEnter EditorMixin.js:686
    routeEnterGuard vue-router.esm.js:2535
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    runQueue vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2397
    step vue-router.esm.js:2084
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    resolveAsyncComponents vue-router.esm.js:2162
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    step vue-router.esm.js:2091
    step vue-router.esm.js:2091
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    created CalendarGrid.vue:235
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    __WEBPACK_DEFAULT_EXPORT__ windowTitleService.js:42
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    runQueue vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2606
    push vue-router.esm.js:3036
    push vue-router.esm.js:3035
    handleEventClick eventClick.js:82
    __WEBPACK_DEFAULT_EXPORT__ eventClick.js:37
    trigger internal-common.js:3680
    node_modules calendar-main.js:183014
    node_modules calendar-main.js:183880
    listenBySelector internal-common.js:270
    EventClicking index.js:1783
    node_modules calendar-main.js:183098
    node_modules calendar-main.js:183098
    registerInteractiveComponent internal.js:761
    componentDidMount internal.js:747
    Preact 4
    node_modules calendar-main.js:183260
    flushSync internal-common.js:2229
    node_modules calendar-main.js:183259
    drained internal-common.js:156
    tryDrain internal-common.js:138
    resume internal-common.js:127
    batchRendering index.js:2070
    changeView internal-common.js:4805
    created CalendarGrid.vue:228
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    __WEBPACK_DEFAULT_EXPORT__ windowTitleService.js:42
    iterator vue-router.esm.js:2362
    step vue-router.esm.js:2087
    runQueue vue-router.esm.js:2095
vue.runtime.esm.js:3065
[Vue warn]: Missing required prop: "name"

found in

---> <NcAppSidebar>
       <EditSidebar> at src/views/EditSidebar.vue
         <NcContent>
           <Calendar> at src/views/Calendar.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:4625
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().

found in

---> <NcDialog>
       <AttachmentsList> at src/components/Editor/Attachments/AttachmentsList.vue
         <NcAppSidebarTab>
           <NcAppSidebarTabs> [...]

2024-06-25 12:18 UTC, st3iny commented
Nice finds. Those are regressions from the nc-vue v8 migration and calendar editor redesign. I'll create a new PR.

I also just pushed a commit to fix uploading attachments.

2024-06-25 14:58 UTC, st3iny approved these changes
Let's go!!! :rocket: :moon:

2024-06-25 17:51 UTC, merged