show additional actions inline
nextcloud/calendar pull request #5906
Opened 2024-04-08 12:02 UTC by szaimen

2024-04-08 14:23 UTC, miaulalala approved these changes
Nice!

2024-04-08 14:35 UTC, jancborchardt requested changes
Some actions are more important or relevant than others here. Showing _all_ of them inline is a bit much and results in a lot of icons without text, which we want to avoid because it is not readily understandable for people who do not use the software every day. :)

- Download and Copy is not as important as "Delete" and "Edit"
- The actions belong more to "Edit" than they do to the close button at the top

That’s why I propose an adjustment like this:
![calendar event](https://github.com/nextcloud/calendar/assets/925062/e5919dd5-5068-4842-858f-446dd93f7b6c)

2024-04-08 14:41 UTC, szaimen commented
> That’s why I propose an adjustment like this:
> ![calendar event](https://private-user-images.githubusercontent.com/925062/320523708-e5919dd5-5068-4842-858f-446dd93f7b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODc1ODgsIm5iZiI6MTcxMjU4NzI4OCwicGF0aCI6Ii85MjUwNjIvMzIwNTIzNzA4LWU1OTE5ZGQ1LTUwNjgtNDg0Mi04NThmLTQ0NmRkOTNmN2I2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNDQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDgyM2JkMTdmYzBhNGU5MjVjYzM5MGFjNzM0OTVkYjM0NDMzNjBiMmMzYWJlNmYwYmVkM2QwMWZhNmMzNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W_oHRbckA6K57uC_rNG4_vdGz5XUH2K8KO5rRI0rkss)

Good idea to move them to the bottom! :)

2025-09-04 15:53 UTC, SebastianKrupinski commented
> Some actions are more important or relevant than others here. Showing _all_ of them inline is a bit much and results in a lot of icons without text, which we want to avoid because it is not readily understandable for people who do not use the software every day. :)
> 
>     * Download and Copy is not as important as "Delete" and "Edit"
> 
>     * The actions belong more to "Edit" than they do to the close button at the top
> 

@jancborchardt @nimishavijay do we still want to do this?

2025-09-25 10:31 UTC, st3iny commented
I like the idea of moving them to the bottom. However, the devil lies in the detail :tm: 

For recurring events we have two delete buttons: this and this+all-future. So we need to render either two buttons, show a menu still or come up with a second modal to let the user decide.

2026-09-05 20:59 UTC, SebastianKrupinski commented
Closing this in favour of https://github.com/nextcloud/calendar/pull/7491

2026-09-05 20:59 UTC, closed without merging