fix: default reminder ui bug
nextcloud/calendar pull request #6249
Opened 2024-08-09 14:27 UTC by abdou6666

#6185 

before : 
![image](https://github.com/user-attachments/assets/33e5d62c-c27a-49e8-a991-42dd3b74dc97)

after : 
![image](https://github.com/user-attachments/assets/a0219fa5-2392-4549-a053-3cbafdf38f64)

2024-08-09 14:36 UTC, hamza221 commented
The text is too long, it will never be displayed fully.  @ChristophWurst would only changing the default reminder be enough to close the issue ?

2024-08-13 17:30 UTC, miaulalala requested changes

2024-08-13 17:30 UTC, miaulalala commented on src/components/AppNavigation/Settings.vue
> +				const label = seconds === 0 ? t('calendar', "at event's start") : t('calendar', "{name} before the event's starts", { name: moment.duration(Math.abs(seconds) * 1000).locale(this.locale).humanize(
Too much text for the width of the field unfortunately.

```suggestion
				const label = seconds === 0 ? t('calendar', "At event start") : moment.duration(Math.abs(seconds) * 1000).locale(this.locale).humanize()
```

2024-08-21 07:44 UTC, miaulalala requested changes

2024-08-21 07:44 UTC, miaulalala commented on src/components/AppNavigation/Settings.vue
> +				const label = seconds === 0 ? t('calendar', "At event start") : moment.duration(Math.abs(seconds) * 1000).locale(this.locale).humanize()
```suggestion
				const label = seconds === 0 ? t('calendar', 'At event start') : moment.duration(Math.abs(seconds) * 1000).locale(this.locale).humanize()
```

CI doesn't like that :see_no_evil: 

If you could change that then we can merge - thanks so much!

2024-08-21 10:22 UTC, hamza221 approved these changes

2024-08-22 07:51 UTC, miaulalala approved these changes

2024-08-22 07:51 UTC, merged

2024-08-22 07:51 UTC, miaulalala commented
No backport due to translations