feat(deps): Add Nextcloud 31 support
nextcloud/calendar pull request #6262
Opened 2024-08-14 11:31 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2024-08-14 11:33 UTC, miaulalala requested changes

2024-08-14 11:33 UTC, miaulalala commented on appinfo/info.xml
> +		<nextcloud min-version="31" max-version="31" />
```suggestion
		<nextcloud min-version="30" max-version="31" />
```

2024-08-14 19:46 UTC, miaulalala approved these changes

2025-01-27 12:25 UTC, st3iny commented
Superseded by https://github.com/nextcloud/calendar/pull/6662

2025-01-27 12:25 UTC, closed without merging