enh(attachmentService, propfindErrorParse): add an error message for when a file is not compatible for windows
nextcloud/calendar pull request #6303
Opened 2024-08-29 15:06 UTC by GVodyanov

Fix https://github.com/nextcloud/calendar/issues/6245

Mostly copied from https://github.com/nextcloud/spreed/blob/main/src/utils/propfindErrorParse.ts

2024-09-02 08:03 UTC, miaulalala requested changes
feat, not enh :wink:

2024-09-02 09:05 UTC, GVodyanov commented
/backport to stable5.0

2024-09-02 09:11 UTC, ChristophWurst approved these changes

2024-09-02 09:18 UTC, merged

2024-09-02 09:47 UTC, miaulalala commented
Does this need a backport to stable4.7 as well?

2024-09-02 10:03 UTC, ChristophWurst commented
No because https://github.com/nextcloud/server/issues/44963 is for 30+

2024-09-04 10:23 UTC, st3iny commented on src/utils/propfindErrorParse.js
> +		console.error(t('spreed', 'Error while parsing a PROPFIND error'), parseError)
Should be sourced from `calendar` instead of `spreed`.