fix: allow adding self to shared event
nextcloud/calendar pull request #6418
Opened 2024-10-13 18:14 UTC by SebastianKrupinski

Resolves: https://github.com/nextcloud/calendar/issues/2659

Modified alreadyInvitedEmails result to NOT exclude the current user by default and to only include actual organize and attendees.

2024-10-15 11:14 UTC, st3iny requested changes
Breaks the attendees tab on new events: `TypeError: Cannot read properties of null (reading 'uri')`.

2024-10-15 11:21 UTC, st3iny commented on src/components/Editor/Invitees/InviteesList.vue
> +				emails.push(removeMailtoPrefix(this.calendarObjectInstance.organizer.uri))
```suggestion
			// A user should be able to invite themselves if they are not the organizer
			const principal = this.principalsStore.getCurrentUserPrincipal
			const organizerUri = this.calendarObjectInstance.organizer?.uri
			if (organizerUri && removeMailtoPrefix(organizerUri) !== principal.emailAddress) {
				emails.push(removeMailtoPrefix(organizerUri))
			} else if (principal) {
				emails.push(principal.emailAddress)
			}
```

Only add the organizer's URI if it isn't equal to the current principal's email address. I should only be able to invite myself if I'm not the organizer.

This was tested locally. See my other comment above.

2024-10-17 06:27 UTC, st3iny commented
Do we want to backport this (since the issue is from 2020)? Or is this too risky because of the recent shared calendar changes in server?

2024-10-31 01:54 UTC, merged

2024-10-31 01:55 UTC, SebastianKrupinski commented
> Do we want to backport this (since the issue is from 2020)? Or is this too risky because of the recent shared calendar changes in server?

We can back port this to 30 for sure and maybe all the way to 28, but I have to look at the code in 29/28 first, it's probably safe just want to make sure.

2024-11-26 09:16 UTC, st3iny commented
/backport to stable5.0