feat:select existing talk roomfor convesations
nextcloud/calendar pull request #6595
Opened 2024-12-30 13:27 UTC by GretaD

fixes #6581

2025-01-06 11:37 UTC, st3iny commented on src/components/Editor/AddTalkModal.vue
**TODO:** Would be nice to have an empty content loading state while the conversations are being fetched.

2025-01-08 10:33 UTC, ChristophWurst commented on src/components/Editor/AddTalkModal.vue
> +			console.debug('Selected conversation:', conversation)
debugging statement

2025-01-08 10:33 UTC, ChristophWurst commented on src/components/Editor/AddTalkModal.vue
> +				console.debug('Conversation URL:', url)
debugging statement

2025-01-08 10:33 UTC, ChristophWurst commented on src/components/Editor/AddTalkModal.vue
> +					console.debug('Applied URL to location:', url)
debugging statement

2025-01-08 10:48 UTC, nimishavijay commented
Looks awesome! Could we try with 28px size for the avatar and 34px height of the whole element? 

I would also suggest to add some spacing between the avatar and the conversation name, maybe one more `--default-grid-baseline` :)

2025-01-08 10:56 UTC, GretaD commented
> Looks awesome! Could we try with 28px size for the avatar and 34px height of the whole element?
> 

sure

> I would also suggest to add some spacing between the avatar and the conversation name, maybe one more `--default-grid-baseline` :)

 `--default-grid-baseline`  is 4px, i have added 5px, so how big should i make it?

2025-01-08 11:31 UTC, nimishavijay approved these changes
Looks great design wise 🚀

2025-01-08 12:06 UTC, tcitworld commented
I'm not fond of 
![image](https://github.com/user-attachments/assets/09ffc9fb-6e73-41e0-aabd-c2174c157387)

The location field is also used for readable information when it's a physical location, not just URLs, and restricting the width again makes it harder to do modifications to a physical address.
Maybe but the button below on subline?

2025-01-08 15:17 UTC, GretaD commented
discussed with Nimisha in private. Having it as google is the best option. @tcitworld does it looks good to you?

![Screenshot from 2025-01-08 16-16-41](https://github.com/user-attachments/assets/045f47e5-963a-49bd-9e1a-384581b774aa)

2025-01-08 16:02 UTC, tcitworld commented
Yup, looks good!

2025-01-08 16:18 UTC, GretaD commented
changed the desc with the latest state

2025-01-08 16:19 UTC, GretaD commented
> Yup, looks good!

thank you, changed the position as suggested by nimisha. Can you please approve if you are happy with it?

2025-01-08 16:40 UTC, tcitworld commented
> changed the position as suggested by nimisha

The button is above the field instead of under it? No opinion on this, but it differs with your previous screenshot.

2025-01-08 17:14 UTC, GretaD commented
> > changed the position as suggested by nimisha
> 
> The button is above the field instead of under it? No opinion on this, but it differs with your previous screenshot.

yes, she sent me a mockup. Sorry if i was not clear. i marked my comment as outdated

2025-01-08 17:56 UTC, tcitworld commented on src/views/EditSidebar.vue
> +		isCreateTalkRoomButtonVisible() {
This is not used.

2025-01-09 13:56 UTC, hamza221 requested changes
render the `add talk`button conditionally only when talk is installed. 
Or show a better error message 
![Screenshot 2568-01-09 at 20 56 25](https://github.com/user-attachments/assets/b464ae01-8751-48c6-b3c8-78df9d411ddc)

2025-01-09 14:04 UTC, st3iny commented
> render the `add talk`button conditionally only when talk is installed. Or show a better error message ![Screenshot 2568-01-09 at 20 56 25](https://private-user-images.githubusercontent.com/40746210/401565900-b464ae01-8751-48c6-b3c8-78df9d411ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzE2MzYsIm5iZiI6MTczNjQzMTMzNiwicGF0aCI6Ii80MDc0NjIxMC80MDE1NjU5MDAtYjQ2NGFlMDEtODc1MS00OGM2LWIzYzgtNzhkZjlkNDExZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE0MDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5M2I5ZGQxZWRmN2Y0ODU3ZGU0OGE1ZDM2YTMxOTg2YjhiMDI5MzM5OGEzOWUxMTE1MDE0OWEyZWZkNTJiMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gy44TzjbgtAJpHeRw2B0MqKCAPvX3JUQDDHUlpI0TSY)

I think you are not on the latest version. Please pull again.

2025-01-09 14:09 UTC, hamza221 approved these changes
LGTM

2025-01-09 14:11 UTC, st3iny reviewed
Styling is a bit off. I fixed it locally and if you have no pending changes, I'll push a commit.

![image](https://github.com/user-attachments/assets/d10b0d80-6cce-45bb-903a-173aa325198f)

2025-01-09 14:13 UTC, ChristophWurst commented
Should https://github.com/nextcloud/calendar/blob/e0c14a65b6dc8955dcf88201bda9a42c2770b2aa/src/components/Editor/Invitees/InviteesList.vue#L42-L47 stay? It means there are now two ways to create a new conversation.

2025-01-09 14:49 UTC, ChristophWurst commented
I mean to remove the previous mechanism and only have the new one.

2025-01-09 14:52 UTC, GretaD commented
> I mean to remove the previous mechanism and only have the new one.

ah, i think thats a good idea. I will do it in a separate pr

2025-01-09 14:57 UTC, st3iny commented
The new file `AddTalkModal.vue` needs a license header:

```
<!--
 - SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 - SPDX-License-Identifier: AGPL-3.0-or-later
 -->
```

2025-01-09 15:20 UTC, ChristophWurst commented
Happy new year btw

2025-01-09 15:29 UTC, GretaD commented
> Happy new year btw

file was created on the 30th of December :)

2025-01-09 15:35 UTC, merged